### ISSUE TITLE
No entry in Wiki possible

### ISSUE THREAD

**Issue by scharph** [arno01/taiga#7] opened 2017-05-10 16:41 UTC
I have no possibility to enter a Wiki text but upload data is possible

With your Docker environment:
![screenshot from 2017-05-10 18-43-11](https://cloud.githubusercontent.com/assets/15950114/25910415/8f4f080e-35b0-11e7-9dc6-a3cfb2012154.png)

as comparision (tree.taiga.io):
![screenshot from 2017-05-10 18-37-41](https://cloud.githubusercontent.com/assets/15950114/25910324/4347e2d2-35b0-11e7-95df-5e05594c6064.png)

Any ideas?

**Comment by arno01** [comment] 2017-09-08 17:00
@scharph I have just tested, everything works for me fine.

I have pushed a small fix, the image will be ready in about an hour.
Would you be able to test it once more?

I have added a ``Quick launch`` section to the README.md, you can try it for a quick test. Just be careful to not remove your docker volumes in case if you are using the same names.

**Comment by arno01** [comment] 2017-09-19 22:23
Closing for now.
Please re-open if the issue is still valid for you.

Thanks.

**Closed by arno01** 2017-09-19 22:23 UTC
